name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        composer install
        composer global require friendsofphp/php-cs-fixer
        composer require sensiolabs/security-checker
        php bin/console security:check
    - name: Test
      run: |
        bin/phpunit tests/Unit
        bin/phpunit tests/Integration
        php vendor/bin/behat